### PR TITLE
adds first cut of an ERD doc

### PR DESCRIPTION
**Pull request by jsqu99**

### CODE REVIEW

**Comment by cas27** [comment]
PayPalPayment, maybe change this something more generic to allow for storage from any other number of 3rd party express checkout systems?

**Comment by jsqu99** [comment]
@cas27 I thought for sure I responded to your comment but I don't see it anywhere :-(

Yeah that payment stuff I'm happy to have lots more conversations about.  Do you have any ideas on how the generic schema woudl look?  I was thinking that some gateways would have different things we'd store (gateway_token_id, gateway_customer_id, gateway_payment_id, etc).

**Comment by cas27** [comment]
@jsqu99 Hard to say on a generic.  

Im thinking to start a `transaction_id` (w/e unique identifier that gateway uses) since that would be the most important info and pretty standard. 

Then perhaps a `reponse:text` as a catchall for the unknown.  Or perhaps JSON store depending on the underlying DB.

**Comment by romul** [comment]
@jsqu99 Payments system is ok in Spree. So we could use the same schema here.

**Comment by jsqu99** [comment]
@romul You are probably correct on the payments comment.  I'm going to just merge this giant ERD in and let's keep improving it.  Sound ok?  If I wait to get it perfect, I'll never get it in the codebase :-)

**Pull request merged**
